### ISSUE TITLE
What is the license for this?

### ISSUE THREAD

**Issue by shiftkey** [tathamoddie/Neo4j.Server.AzureWorkerHost#1]
I see that the .NET [Neo4jClient](https://bitbucket.org/Readify/neo4jclient/wiki/Home) is licensed under MS-PL. Should I expect a similar license on this?

**Comment by tathamoddie** [comment]
Backlog-ed: https://trello.com/c/2r1lVCQv

**Comment by shiftkey** [comment]
I really can't recall the context for originally asking about this. Whatever.
